# Generated by Django 5.0 on 2024-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='files',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
