# Generated by Django 5.0 on 2024-02-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_rename_files_file_document_remove_file_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
